version: '3'
services:
  django-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django-backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    command: /start
