version: '3'
services:
  lighthouse:
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./reports:/home/chrome/reports
    ports:
      - "5000:5000"
    restart: unless-stopped
    command: /app/start
